name: Atualizar Dados e Gráficos
on:
  push:
    branches: [ main ]
jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Instalar dependências
      run: |
        python -m pip install --upgrade pip
        pip install pandas openpyxl
    - name: Processar planilha
      run: python processar_planilha.py
    - name: Commit mudanças
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add docs/data.json
        git commit -m "Atualizar dados dos gráficos" || echo "Nenhuma mudança"
        git push
